### ISSUE TITLE
Error when connecting to Dockerized HumHub Instance

### ISSUE THREAD

**Issue by FabianSimonGross** [humhub/app#112]
Hey,

I'm not particular sure if that's an administration issue on my side.
But when I try connecting with my Instance running in a dockerized environment it says: ERR_CLEARTEXT_NOT_PERMITTED

I'd like to test around a bit with the App.

Regards

**Comment by ArchBlood** [comment]
Are you using a reverse proxy or unsecure domain as this only happens when trying to access a web page that wants to transmit cleartext or unsecure Information, Android blocks this to protect user data by default.

**Comment by FabianSimonGross** [comment]
I'm using it behind a traefik reverse proxy yes.
Is there any way to "avoid" that?

**Comment by ArchBlood** [comment]
There are a few ways to fix the issue, namely in the configuration allow for `cleartext`, not advised but possible, the other is for you to make sure that your connection is secure through the reverse proxy.

Overall it would be up to @luke- to have it implemented, but again I wouldn't recommend allowing it because it could cause more harm than good.

**Comment by FabianSimonGross** [comment]
Thanks I figured it out now.

In our docker-container the settings for running it behind a reverse-proxy have not been set properly.

This Part of the Docs from HumHub is necessary to be completed: https://docs.humhub.org/docs/admin/reverse-proxy/

So far thank you for that project btw. we have been looking for something like this for at least 3 years by now.
