### ISSUE TITLE
Sometimes new connect necessary

### ISSUE THREAD

**Issue by JK742020** [humhub/app#193]
Many times the app opens as expected. 
1. Clicking the icon
2. Dashboard of my network

Sometimes (1 out of 10 maybe) it is necessary to connect again from the screen where the url needs to be placed (url is still there).

**Comment by VCRP-fetzer** [comment]
I just did a clean install of the app today (v1.0.99) and can observe the same issue. After force-quitting the app, I had to log in again.

**Comment by VCRP-fetzer** [comment]
On 1.0.100 I still get the connect dialogue after a force-quit, but the URL is filled in and I don't have to authenticate. A colleague of mine is seeing the same behaviour.

**Comment by marc-farre** [comment]
I've tested on Android 10 and Android 13.
Version prior to 1.0.100, I confirm the issue.

But, if I:
1. uninstall HumHub app
2. install v1.0.100
3. login (this is required, otherwise it is intended to show the URL form)
I don't have the issue anymore.

Do you confirm, on your side, you still have the issue after these 3 steps?
If yes, then let us know which Android version you have.

@luke- On Android Play store, we still have v1.0.99. Maybe we could release v1.0.100?

**Comment by luke-** [comment]
@marc-farre Thanks,  v1.0.100 is now availble

**Comment by marc-farre** [comment]
@JK742020 If this issue is solved, can you close it? Thanks.
