### ISSUE TITLE
In iOS app, Google-login does not work because Google does not like the embedded browser

### ISSUE THREAD

**Issue by almarklein** [humhub/app#244]
I can click the button to sign-in with Google, fill in my Google email adress, but in the next step (where normally I'd be asked for my password) I get this:

<img width=250 src='https://github.com/user-attachments/assets/9f4f7131-71f2-4832-8c16-c8e2c25352c2' /><br>

Clicking *learn more* produces:
<img width=250 src='https://github.com/user-attachments/assets/133fdfce-5bef-4fbf-9084-275c50a7948a' />

**Comment by marc-farre** [comment]
@PrimozRatej any idea?

A quick research with https://claude.ai/ gives some pointers (I didn't search more, let me know if I can help):

1. Custom Tabs / SFSafariViewController:
   Instead of using a WebView, it's recommended to use Custom Tabs (on Android) or SFSafariViewController (on iOS) for better security and user experience with OAuth flows.

2. App-Bound Domains:
   Google and other providers are increasingly requiring the use of app-bound domains for authentication flows within apps.

3. User-Agent String:
   The internal browser might have a user-agent string that Google doesn't recognize or trust.

4. Missing OAuth 2.0 PKCE:
   Proof Key for Code Exchange (PKCE) is an extension to OAuth 2.0 that provides additional security for mobile apps.

Here are some steps you can take to address this issue:

1. Use Custom Tabs or SFSafariViewController:
   If you're using Flutter, you can use the `flutter_inappwebview` package, which supports these more secure browser views. Here's a basic example of how you might implement this:

   ```dart
import 'package:flutter/material.dart';
   import 'package:flutter_inappwebview/flutter_inappwebview.dart';

   class SecureWebView extends StatelessWidget {
     final String url;

     SecureWebView({required this.url});

     @override
     Widget build(BuildContext context) {
       return Scaffold(
         appBar: AppBar(title: Text('Secure Web View')),
         body: InAppWebView(
           initialUrlRequest: URLRequest(url: Uri.parse(url)),
           initialOptions: InAppWebViewGroupOptions(
             crossPlatform: InAppWebViewOptions(
               useShouldOverrideUrlLoading: true,
               useOnLoadResource: true,
             ),
           ),
           onWebViewCreated: (InAppWebViewController controller) {
             // You can add additional configuration here if needed
           },
         ),
       );
     }
   }
   
```

   This approach uses a more secure web view that's less likely to be flagged by Google.

2. Implement App Links / Universal Links:
   Set up app links (Android) or universal links (iOS) for your domain. This allows your app to handle the authentication redirect securely.

3. Update User-Agent:
   If you must use a WebView, try setting a user-agent string that mimics a standard mobile browser. However, be aware that this might violate Google's terms of service.

4. Implement PKCE:
   If you're handling the OAuth flow yourself, implement PKCE. This adds an extra layer of security that Google may require.

**Comment by almarklein** [comment]
Not sure if this is relevant, but on most apps, when I sign-in with Google, it will already show my Google avatar and I only have to insert my password. With the current flow, I also have to provide my email. From what I understand, when my avatar is shown, the embedded browser is the builtin browser, or at least somehow shares cookies or something.

**Comment by almarklein** [comment]
@marc-farre I did not mean to use native auth. I meant that other apps also use an embedded browser for this flow, but it's likely a different kind of browser, because in these cases it remembered my Google account.

**Comment by PrimozRatej** [comment]
@marc-farre My first guess would be the User-Agent. We encountered a similar issue with Android some time ago. I'll look into it.

**Comment by vilmosnagy** [comment]
> We encountered a similar issue with Android some time ago. I'll look into it.

Same for me on Android. Any ideas?

**Comment by almarklein** [comment]
I can confirm that the latest version (with #258) fixes the problem for iOS. Closing since this issue was for specifically for iOS. @vilmosnagy could you try the latest version (v1.0.123) and open a new issue if it persists?

**Comment by vilmosnagy** [comment]
> could you try the latest version (v1.0.123) and open a new issue if it persists?

Where could I see this version for Android? Is it deployed to the play store? Thanks,

**Comment by almarklein** [comment]
https://play.google.com/store/apps/details?id=com.humhub.app (shows the update date, but not the version)

**Comment by vilmosnagy** [comment]
hm, the play store on my phone shows that the last update was on the 19th.

![image](https://github.com/user-attachments/assets/3a93aa8f-588f-4611-a0c2-8e67380bc64a)

Should I join the beta? When will it roll out to the stable branch?
