### ISSUE TITLE
Adjust Github Workflow 

### ISSUE THREAD

**Issue by luke-** [humhub/app#53]
- Test Workflow with new repository name
- Rename workflow to `version-release`
- Only trigger this, on new Git version tag e.g. https://github.com/humhub/wiki/blob/master/.github/workflows/marketplace-upload.yml#L1-L4
- Doc steps for version release

**Comment by PrimozRatej** [comment]
We have modified our version-release workflow to only trigger on new Git version tags that follow a specific format. 
The tag format is "`v0.0.1-2`"
- "`v0.0.1`" represents the release version for Github Releases.
- "`0.0.1`" represents the app version.
- "`2`" represents the Build Version code for Google Play Store. 
The Google Play Store requires that the version code be greater than the previously submitted version code, regardless of the version number.  [source](https://developer.android.com/studio/publish/versioning)
Previously, the version code was set from the buildNumber of the Github build, but when it was moved to this repository, the buildNumber was reset to 1. 
As a result, we encountered an error when submitting a new build with version code 1 because the previous build's version code was lower. 
Unfortunately, the buildNumber on Github cannot be manually overwritten. 
Therefore, I have decided to use this tag naming convention to manually define the versionCode.
