### ISSUE TITLE
Notification opens the Dashboard instead of the related content

### ISSUE THREAD

**Issue by marc-farre** [humhub/app#95]
When clicking on the notification, the mobile app opens the Dashboard instead of the related content.

**Comment by funkycram** [comment]
The problem is still present on release v1.0.66 (app-arm64-v8a-release.apk).

**Comment by luke-** [comment]
@PrimozRatej For me the issue is still present.

Do you need help regarding a demo?

**Comment by PrimozRatej** [comment]
@luke-  Will look into it this evening. No thanks, the issue is entirely on the mobile side.

**Comment by marc-farre** [comment]
@PrimozRatej any news about this issue? Thanks.

**Comment by luke-** [comment]
@marc-farre What do we do if there is no reliable option here?

**Comment by marc-farre** [comment]
I don't know... Maybe displaying the notification list page (`/notification/overview`) instead of the Dashboard?

**Comment by PrimozRatej** [comment]
Hello @luke- , @marc-farre I created a PR, The problem here was that the notification we get when the app is terminated differs from when the app is running and have access to override and append the channels. I now fixed it so that the app uses def. channel that gets from Firebase, I tested it in all 3 states (terminated, background, foreground), It should work now.

**Comment by marc-farre** [comment]
Tested, works great, thanks @PrimozRatej !

@luke- On my point of view, when https://github.com/humhub/app/issues/96 is implemented (hopefully in Humhub 1.15 final release), and perhaps when https://github.com/humhub/app/issues/102 is fixed, the app is mature enough to be available on Android marketplace.
